/*
 * Landelijke tabellen
 *
 * API voor het ontsluiten van landelijke tabellen die op de website van BZK worden gepubliceerd.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITabelwaardenApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een enkele waarde uit een landelijke tabel.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde.</param>
        /// <returns>Waarde</returns>
        Waarde GetWaarde(string tabelidentificatie, string code);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een enkele waarde uit een landelijke tabel.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde.</param>
        /// <returns>ApiResponse of Waarde</returns>
        ApiResponse<Waarde> GetWaardeWithHttpInfo(string tabelidentificatie, string code);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de tabelwaarden van een landelijke tabel.&lt;br&gt;Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. &lt;br&gt; Als de parameter &lt;b&gt; inclusief beeindigd &lt;/b&gt; met waarde &lt;i&gt; true &lt;/i&gt;  wordt meegegeven bij de call worden ook beeindigde waarden geretourneerd.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde. (optional)</param>
        /// <param name="omschrijving">De omschrijving van de tabelwaarde. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;. &lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="inclusiefbeeindigd">De indicatie waarmee aangegeven wordt of beëindigde waarden moeten worden meegeleverd. Default worden alleen actuele tabelwaarden geretourneerd. Wanneer deze wordt opgenomen met de waarde true, dan worden ook beëindigde tabelwaarden meegeleverd. (optional)</param>
        /// <returns>WaardeCollectie</returns>
        WaardeCollectie GetWaarden(string tabelidentificatie, string code = default(string), string omschrijving = default(string), bool? inclusiefbeeindigd = default(bool?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de tabelwaarden van een landelijke tabel.&lt;br&gt;Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. &lt;br&gt; Als de parameter &lt;b&gt; inclusief beeindigd &lt;/b&gt; met waarde &lt;i&gt; true &lt;/i&gt;  wordt meegegeven bij de call worden ook beeindigde waarden geretourneerd.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde. (optional)</param>
        /// <param name="omschrijving">De omschrijving van de tabelwaarde. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;. &lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="inclusiefbeeindigd">De indicatie waarmee aangegeven wordt of beëindigde waarden moeten worden meegeleverd. Default worden alleen actuele tabelwaarden geretourneerd. Wanneer deze wordt opgenomen met de waarde true, dan worden ook beëindigde tabelwaarden meegeleverd. (optional)</param>
        /// <returns>ApiResponse of WaardeCollectie</returns>
        ApiResponse<WaardeCollectie> GetWaardenWithHttpInfo(string tabelidentificatie, string code = default(string), string omschrijving = default(string), bool? inclusiefbeeindigd = default(bool?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITabelwaardenApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een enkele waarde uit een landelijke tabel.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Waarde</returns>
        System.Threading.Tasks.Task<Waarde> GetWaardeAsync(string tabelidentificatie, string code, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een enkele waarde uit een landelijke tabel.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Waarde)</returns>
        System.Threading.Tasks.Task<ApiResponse<Waarde>> GetWaardeWithHttpInfoAsync(string tabelidentificatie, string code, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de tabelwaarden van een landelijke tabel.&lt;br&gt;Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. &lt;br&gt; Als de parameter &lt;b&gt; inclusief beeindigd &lt;/b&gt; met waarde &lt;i&gt; true &lt;/i&gt;  wordt meegegeven bij de call worden ook beeindigde waarden geretourneerd.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde. (optional)</param>
        /// <param name="omschrijving">De omschrijving van de tabelwaarde. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;. &lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="inclusiefbeeindigd">De indicatie waarmee aangegeven wordt of beëindigde waarden moeten worden meegeleverd. Default worden alleen actuele tabelwaarden geretourneerd. Wanneer deze wordt opgenomen met de waarde true, dan worden ook beëindigde tabelwaarden meegeleverd. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WaardeCollectie</returns>
        System.Threading.Tasks.Task<WaardeCollectie> GetWaardenAsync(string tabelidentificatie, string code = default(string), string omschrijving = default(string), bool? inclusiefbeeindigd = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de tabelwaarden van een landelijke tabel.&lt;br&gt;Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. &lt;br&gt; Als de parameter &lt;b&gt; inclusief beeindigd &lt;/b&gt; met waarde &lt;i&gt; true &lt;/i&gt;  wordt meegegeven bij de call worden ook beeindigde waarden geretourneerd.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde. (optional)</param>
        /// <param name="omschrijving">De omschrijving van de tabelwaarde. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;. &lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="inclusiefbeeindigd">De indicatie waarmee aangegeven wordt of beëindigde waarden moeten worden meegeleverd. Default worden alleen actuele tabelwaarden geretourneerd. Wanneer deze wordt opgenomen met de waarde true, dan worden ook beëindigde tabelwaarden meegeleverd. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WaardeCollectie)</returns>
        System.Threading.Tasks.Task<ApiResponse<WaardeCollectie>> GetWaardenWithHttpInfoAsync(string tabelidentificatie, string code = default(string), string omschrijving = default(string), bool? inclusiefbeeindigd = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITabelwaardenApi : ITabelwaardenApiSync, ITabelwaardenApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TabelwaardenApi : ITabelwaardenApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TabelwaardenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TabelwaardenApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TabelwaardenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TabelwaardenApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TabelwaardenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TabelwaardenApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TabelwaardenApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TabelwaardenApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een enkele waarde uit een landelijke tabel.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde.</param>
        /// <returns>Waarde</returns>
        public Waarde GetWaarde(string tabelidentificatie, string code)
        {
            Org.OpenAPITools.Client.ApiResponse<Waarde> localVarResponse = GetWaardeWithHttpInfo(tabelidentificatie, code);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een enkele waarde uit een landelijke tabel.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde.</param>
        /// <returns>ApiResponse of Waarde</returns>
        public Org.OpenAPITools.Client.ApiResponse<Waarde> GetWaardeWithHttpInfo(string tabelidentificatie, string code)
        {
            // verify the required parameter 'tabelidentificatie' is set
            if (tabelidentificatie == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tabelidentificatie' when calling TabelwaardenApi->GetWaarde");

            // verify the required parameter 'code' is set
            if (code == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'code' when calling TabelwaardenApi->GetWaarde");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("tabelidentificatie", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tabelidentificatie)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Org.OpenAPITools.Client.ClientUtils.ParameterToString(code)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<Waarde>("/tabellen/{tabelidentificatie}/waarden/{code}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetWaarde", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een enkele waarde uit een landelijke tabel.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Waarde</returns>
        public async System.Threading.Tasks.Task<Waarde> GetWaardeAsync(string tabelidentificatie, string code, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Waarde> localVarResponse = await GetWaardeWithHttpInfoAsync(tabelidentificatie, code, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een enkele waarde uit een landelijke tabel.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Waarde)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Waarde>> GetWaardeWithHttpInfoAsync(string tabelidentificatie, string code, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tabelidentificatie' is set
            if (tabelidentificatie == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tabelidentificatie' when calling TabelwaardenApi->GetWaarde");

            // verify the required parameter 'code' is set
            if (code == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'code' when calling TabelwaardenApi->GetWaarde");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("tabelidentificatie", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tabelidentificatie)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Org.OpenAPITools.Client.ClientUtils.ParameterToString(code)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Waarde>("/tabellen/{tabelidentificatie}/waarden/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetWaarde", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Het ophalen van de tabelwaarden van een landelijke tabel.&lt;br&gt;Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. &lt;br&gt; Als de parameter &lt;b&gt; inclusief beeindigd &lt;/b&gt; met waarde &lt;i&gt; true &lt;/i&gt;  wordt meegegeven bij de call worden ook beeindigde waarden geretourneerd.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde. (optional)</param>
        /// <param name="omschrijving">De omschrijving van de tabelwaarde. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;. &lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="inclusiefbeeindigd">De indicatie waarmee aangegeven wordt of beëindigde waarden moeten worden meegeleverd. Default worden alleen actuele tabelwaarden geretourneerd. Wanneer deze wordt opgenomen met de waarde true, dan worden ook beëindigde tabelwaarden meegeleverd. (optional)</param>
        /// <returns>WaardeCollectie</returns>
        public WaardeCollectie GetWaarden(string tabelidentificatie, string code = default(string), string omschrijving = default(string), bool? inclusiefbeeindigd = default(bool?))
        {
            Org.OpenAPITools.Client.ApiResponse<WaardeCollectie> localVarResponse = GetWaardenWithHttpInfo(tabelidentificatie, code, omschrijving, inclusiefbeeindigd);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Het ophalen van de tabelwaarden van een landelijke tabel.&lt;br&gt;Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. &lt;br&gt; Als de parameter &lt;b&gt; inclusief beeindigd &lt;/b&gt; met waarde &lt;i&gt; true &lt;/i&gt;  wordt meegegeven bij de call worden ook beeindigde waarden geretourneerd.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde. (optional)</param>
        /// <param name="omschrijving">De omschrijving van de tabelwaarde. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;. &lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="inclusiefbeeindigd">De indicatie waarmee aangegeven wordt of beëindigde waarden moeten worden meegeleverd. Default worden alleen actuele tabelwaarden geretourneerd. Wanneer deze wordt opgenomen met de waarde true, dan worden ook beëindigde tabelwaarden meegeleverd. (optional)</param>
        /// <returns>ApiResponse of WaardeCollectie</returns>
        public Org.OpenAPITools.Client.ApiResponse<WaardeCollectie> GetWaardenWithHttpInfo(string tabelidentificatie, string code = default(string), string omschrijving = default(string), bool? inclusiefbeeindigd = default(bool?))
        {
            // verify the required parameter 'tabelidentificatie' is set
            if (tabelidentificatie == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tabelidentificatie' when calling TabelwaardenApi->GetWaarden");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "application/problem+json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("tabelidentificatie", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tabelidentificatie)); // path parameter
            if (code != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "code", code));
            }
            if (omschrijving != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "omschrijving", omschrijving));
            }
            if (inclusiefbeeindigd != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "inclusiefbeeindigd", inclusiefbeeindigd));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<WaardeCollectie>("/tabellen/{tabelidentificatie}/waarden", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetWaarden", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Het ophalen van de tabelwaarden van een landelijke tabel.&lt;br&gt;Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. &lt;br&gt; Als de parameter &lt;b&gt; inclusief beeindigd &lt;/b&gt; met waarde &lt;i&gt; true &lt;/i&gt;  wordt meegegeven bij de call worden ook beeindigde waarden geretourneerd.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde. (optional)</param>
        /// <param name="omschrijving">De omschrijving van de tabelwaarde. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;. &lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="inclusiefbeeindigd">De indicatie waarmee aangegeven wordt of beëindigde waarden moeten worden meegeleverd. Default worden alleen actuele tabelwaarden geretourneerd. Wanneer deze wordt opgenomen met de waarde true, dan worden ook beëindigde tabelwaarden meegeleverd. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WaardeCollectie</returns>
        public async System.Threading.Tasks.Task<WaardeCollectie> GetWaardenAsync(string tabelidentificatie, string code = default(string), string omschrijving = default(string), bool? inclusiefbeeindigd = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<WaardeCollectie> localVarResponse = await GetWaardenWithHttpInfoAsync(tabelidentificatie, code, omschrijving, inclusiefbeeindigd, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Het ophalen van de tabelwaarden van een landelijke tabel.&lt;br&gt;Als er op omschrijving of code gezocht wordt worden alleen actuele waarden geretourneerd. &lt;br&gt; Als de parameter &lt;b&gt; inclusief beeindigd &lt;/b&gt; met waarde &lt;i&gt; true &lt;/i&gt;  wordt meegegeven bij de call worden ook beeindigde waarden geretourneerd.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="code">De code, behorende bij de tabelwaarde. (optional)</param>
        /// <param name="omschrijving">De omschrijving van de tabelwaarde. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;. &lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="inclusiefbeeindigd">De indicatie waarmee aangegeven wordt of beëindigde waarden moeten worden meegeleverd. Default worden alleen actuele tabelwaarden geretourneerd. Wanneer deze wordt opgenomen met de waarde true, dan worden ook beëindigde tabelwaarden meegeleverd. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WaardeCollectie)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<WaardeCollectie>> GetWaardenWithHttpInfoAsync(string tabelidentificatie, string code = default(string), string omschrijving = default(string), bool? inclusiefbeeindigd = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tabelidentificatie' is set
            if (tabelidentificatie == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'tabelidentificatie' when calling TabelwaardenApi->GetWaarden");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "application/problem+json"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("tabelidentificatie", Org.OpenAPITools.Client.ClientUtils.ParameterToString(tabelidentificatie)); // path parameter
            if (code != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "code", code));
            }
            if (omschrijving != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "omschrijving", omschrijving));
            }
            if (inclusiefbeeindigd != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "inclusiefbeeindigd", inclusiefbeeindigd));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<WaardeCollectie>("/tabellen/{tabelidentificatie}/waarden", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetWaarden", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
