/*
 * Landelijke tabellen
 * API voor het ontsluiten van landelijke tabellen die op de website van BZK worden gepubliceerd.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Landelijke tabellen zoals ontsloten door het RvIG.
 */
@ApiModel(description = "Landelijke tabellen zoals ontsloten door het RvIG.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-16T17:17:28.473148Z[Etc/UTC]")
public class Tabel {
  public static final String SERIALIZED_NAME_TABELIDENTIFICATIE = "tabelidentificatie";
  @SerializedName(SERIALIZED_NAME_TABELIDENTIFICATIE)
  private String tabelidentificatie;

  public static final String SERIALIZED_NAME_OMSCHRIJVING = "omschrijving";
  @SerializedName(SERIALIZED_NAME_OMSCHRIJVING)
  private String omschrijving;


  public Tabel tabelidentificatie(String tabelidentificatie) {
    
    this.tabelidentificatie = tabelidentificatie;
    return this;
  }

   /**
   * De identificatie, behorende bij de tabel.
   * @return tabelidentificatie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Reden_Nationaliteit", value = "De identificatie, behorende bij de tabel.")

  public String getTabelidentificatie() {
    return tabelidentificatie;
  }


  public void setTabelidentificatie(String tabelidentificatie) {
    this.tabelidentificatie = tabelidentificatie;
  }


  public Tabel omschrijving(String omschrijving) {
    
    this.omschrijving = omschrijving;
    return this;
  }

   /**
   * De omschrijving van de landelijke tabel
   * @return omschrijving
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Reden opnemen - beeindigen Nationaliteit", value = "De omschrijving van de landelijke tabel")

  public String getOmschrijving() {
    return omschrijving;
  }


  public void setOmschrijving(String omschrijving) {
    this.omschrijving = omschrijving;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tabel tabel = (Tabel) o;
    return Objects.equals(this.tabelidentificatie, tabel.tabelidentificatie) &&
        Objects.equals(this.omschrijving, tabel.omschrijving);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tabelidentificatie, omschrijving);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tabel {\n");
    sb.append("    tabelidentificatie: ").append(toIndentedString(tabelidentificatie)).append("\n");
    sb.append("    omschrijving: ").append(toIndentedString(omschrijving)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

