/*
 * Landelijke tabellen
 *
 * API voor het ontsluiten van landelijke tabellen die op de website van BZK worden gepubliceerd.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITabellenApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een enkele landelijke tabel
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <returns>Tabel</returns>
        Tabel GetTabel (string tabelidentificatie);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een enkele landelijke tabel
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <returns>ApiResponse of Tabel</returns>
        ApiResponse<Tabel> GetTabelWithHttpInfo (string tabelidentificatie);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van een collectie landelijke tabellen.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel. (optional)</param>
        /// <param name="omschrijving">De naam van de tabel. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;.&lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <returns>TabelCollectie</returns>
        TabelCollectie GetTabellen (string tabelidentificatie = default(string), string omschrijving = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van een collectie landelijke tabellen.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel. (optional)</param>
        /// <param name="omschrijving">De naam van de tabel. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;.&lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <returns>ApiResponse of TabelCollectie</returns>
        ApiResponse<TabelCollectie> GetTabellenWithHttpInfo (string tabelidentificatie = default(string), string omschrijving = default(string));
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een enkele landelijke tabel
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Tabel</returns>
        System.Threading.Tasks.Task<Tabel> GetTabelAsync (string tabelidentificatie, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een enkele landelijke tabel
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Tabel)</returns>
        System.Threading.Tasks.Task<ApiResponse<Tabel>> GetTabelWithHttpInfoAsync (string tabelidentificatie, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van een collectie landelijke tabellen.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel. (optional)</param>
        /// <param name="omschrijving">De naam van de tabel. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;.&lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TabelCollectie</returns>
        System.Threading.Tasks.Task<TabelCollectie> GetTabellenAsync (string tabelidentificatie = default(string), string omschrijving = default(string), CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van een collectie landelijke tabellen.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel. (optional)</param>
        /// <param name="omschrijving">De naam van de tabel. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;.&lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TabelCollectie)</returns>
        System.Threading.Tasks.Task<ApiResponse<TabelCollectie>> GetTabellenWithHttpInfoAsync (string tabelidentificatie = default(string), string omschrijving = default(string), CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TabellenApi : ITabellenApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TabellenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TabellenApi(String basePath)
        {
            this.Configuration = new Org.OpenAPITools.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TabellenApi"/> class
        /// </summary>
        /// <returns></returns>
        public TabellenApi()
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.Default;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TabellenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TabellenApi(Org.OpenAPITools.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.OpenAPITools.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een enkele landelijke tabel
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <returns>Tabel</returns>
        public Tabel GetTabel (string tabelidentificatie)
        {
             ApiResponse<Tabel> localVarResponse = GetTabelWithHttpInfo(tabelidentificatie);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een enkele landelijke tabel
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <returns>ApiResponse of Tabel</returns>
        public ApiResponse<Tabel> GetTabelWithHttpInfo (string tabelidentificatie)
        {
            // verify the required parameter 'tabelidentificatie' is set
            if (tabelidentificatie == null)
                throw new ApiException(400, "Missing required parameter 'tabelidentificatie' when calling TabellenApi->GetTabel");

            var localVarPath = "/tabellen/{tabelidentificatie}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (tabelidentificatie != null) localVarPathParams.Add("tabelidentificatie", this.Configuration.ApiClient.ParameterToString(tabelidentificatie)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTabel", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Tabel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Tabel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Tabel)));
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een enkele landelijke tabel
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Tabel</returns>
        public async System.Threading.Tasks.Task<Tabel> GetTabelAsync (string tabelidentificatie, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Tabel> localVarResponse = await GetTabelWithHttpInfoAsync(tabelidentificatie, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Het ophalen van de gegevens van een enkele landelijke tabel
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Tabel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Tabel>> GetTabelWithHttpInfoAsync (string tabelidentificatie, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'tabelidentificatie' is set
            if (tabelidentificatie == null)
                throw new ApiException(400, "Missing required parameter 'tabelidentificatie' when calling TabellenApi->GetTabel");

            var localVarPath = "/tabellen/{tabelidentificatie}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (tabelidentificatie != null) localVarPathParams.Add("tabelidentificatie", this.Configuration.ApiClient.ParameterToString(tabelidentificatie)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTabel", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Tabel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Tabel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Tabel)));
        }

        /// <summary>
        ///  Het ophalen van een collectie landelijke tabellen.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel. (optional)</param>
        /// <param name="omschrijving">De naam van de tabel. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;.&lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <returns>TabelCollectie</returns>
        public TabelCollectie GetTabellen (string tabelidentificatie = default(string), string omschrijving = default(string))
        {
             ApiResponse<TabelCollectie> localVarResponse = GetTabellenWithHttpInfo(tabelidentificatie, omschrijving);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Het ophalen van een collectie landelijke tabellen.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel. (optional)</param>
        /// <param name="omschrijving">De naam van de tabel. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;.&lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <returns>ApiResponse of TabelCollectie</returns>
        public ApiResponse<TabelCollectie> GetTabellenWithHttpInfo (string tabelidentificatie = default(string), string omschrijving = default(string))
        {

            var localVarPath = "/tabellen";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (tabelidentificatie != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "tabelidentificatie", tabelidentificatie)); // query parameter
            if (omschrijving != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "omschrijving", omschrijving)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTabellen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TabelCollectie>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TabelCollectie) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TabelCollectie)));
        }

        /// <summary>
        ///  Het ophalen van een collectie landelijke tabellen.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel. (optional)</param>
        /// <param name="omschrijving">De naam van de tabel. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;.&lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of TabelCollectie</returns>
        public async System.Threading.Tasks.Task<TabelCollectie> GetTabellenAsync (string tabelidentificatie = default(string), string omschrijving = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<TabelCollectie> localVarResponse = await GetTabellenWithHttpInfoAsync(tabelidentificatie, omschrijving, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Het ophalen van een collectie landelijke tabellen.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tabelidentificatie">De identificatie van een landelijke tabel. (optional)</param>
        /// <param name="omschrijving">De naam van de tabel. &lt;br&gt; Bij het zoeken mag er gebruik worden gemaakt van &lt;b&gt;[wildcards](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/wildcard.feature)&lt;/b&gt;.&lt;br&gt;Zoeken is &lt;b&gt;[case-Insensitive](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/case_insensitive.feature)&lt;/b&gt;&lt;/a&gt; (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (TabelCollectie)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TabelCollectie>> GetTabellenWithHttpInfoAsync (string tabelidentificatie = default(string), string omschrijving = default(string), CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/tabellen";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (tabelidentificatie != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "tabelidentificatie", tabelidentificatie)); // query parameter
            if (omschrijving != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "omschrijving", omschrijving)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetTabellen", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TabelCollectie>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (TabelCollectie) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TabelCollectie)));
        }

    }
}
